### ISSUE TITLE
sox node error - data is not defined

### ISSUE THREAD

**Issue by andreabat** [NGRP/node-red-contrib-viseo#157]
When using the sox node, an unhandled promise rejection takes place.

(node:11860) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at input (/home/andreab/.node-red/node_modules/node-red-contrib-viseo-sox/node-sox-command.js:45:53)

By looking at the code it appears as if the "data" variable should be "msg" instead , but it's my guess.

**Comment by luca-ferrari-roma** [comment]
Hi, also me, when I use "node-red-contrib-viseo-ffmpeg" node I receive a similar error as below.
Some help?

4 Feb 17:28:22 - [info] Started flows
(node:22456) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at input (C:\Users\ferrluca\.node-red\node_modules\node-red-contrib-viseo-ffmpeg\node-ffmpeg-command.js:45:53)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
